## 배포 워크플로우

name: Deploy Workflow

on:
    push:
        branches:
            - main
            - production

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Cache node modules
              uses: actions/cache@v4
              id: cache
              with:
                  path: node_modules
                  key: npm-packages-${{ hashFiles('**/yarn.lock') }}

            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: yarn install

            - name: Set environment variables
              run: |
                  if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
                    echo "ENVIRONMENT=dev" >> $GITHUB_ENV
                    echo "BUILD_COMMAND=beta" >> $GITHUB_ENV
                    echo "DOCKER_TAG=dev" >> $GITHUB_ENV
                    echo "BUILD_FILE=beta" >> $GITHUB_ENV
                  else
                    echo "ENVIRONMENT=prod" >> $GITHUB_ENV
                    echo "BUILD_COMMAND=build" >> $GITHUB_ENV
                    echo "DOCKER_TAG=prod" >> $GITHUB_ENV
                    echo "BUILD_FILE=dist" >> $GITHUB_ENV
                  fi

            - name: Build
              run: yarn ${{ env.BUILD_COMMAND }}

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and Push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/mokkoji:${{ env.DOCKER_TAG }}

            # 아래 ec2 에 hub의 이미지를 가져와서 실행하는 명령 추가 (ec2 설정완료 후 진행)
